### ISSUE TITLE
Buttons not available when using SUBFOLDER options

### ISSUE THREAD

**Issue by PriamX** [linuxserver/docker-emulatorjs#14]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
"Rom Management", "Config Management", File Management", and "Download" buttons are expect to be present and working.

## Current Behavior
When using the SUBFOLDER options, although the text for the buttons is present, the actually clickable buttons are not present.

## Steps to Reproduce

1. Using the docker compose files set a "SUBFOLDER" option.
2. Deploy the container.
3. Visit http://ipaddress:3000/subfolder 
4. Buttons are not present, however, all other text is.

## Environment
**OS:** Fedora 34, Docker 20.10.12
**CPU architecture:** x86_64
**How docker service was installed:**
`dnf install docker` (from fedora repo)

## Command used to create docker container (run/create/compose/screenshot)\
```
version: "2"
networks:
  plexnet:
    external:
      name: homenet
services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs
    container_name: emulatorjs
    environment:
      - PUID=981
      - PGID=100
      - TZ=America/Denver
      - SUBFOLDER=/emulatorjs
    volumes:
      - /media/docker/appdata/emulatorjs:/data
    ports:
      - 3000:3000
      - 8084:80
      - 4001:4001 #optional
    networks:
      - homenet
    restart: unless-stopped
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    981
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Initializing daemon...
go-ipfs version: 0.8.0-3a7b65e49c
Repo version: 11
System version: amd64/linux
Golang version: go1.16.10
2022/01/11 20:00:23 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic
Swarm listening on /ip4/172.20.0.3/tcp/4001
Swarm listening on /ip4/172.20.0.3/udp/4001/quic
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.0.0.1/udp/4001/quic
Swarm announcing /ip4/(redacted)/udp/4001/quic
Swarm announcing /ip4/172.20.0.3/tcp/4001
Swarm announcing /ip4/172.20.0.3/udp/4001/quic
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
```
